$('.c-btn--header-menu').on('click',function(){
      $('.l-sidebar').addClass('open');
      $('.l-sidebar__drawer-bg').fadeToggle();
      $('html').css('overflow','hidden');
    }
  );
  $('.c-btn--menu-close').on('click',function(){
    $('.l-sidebar').removeClass('open');
    $('.l-sidebar__drawer-bg').fadeToggle();
    $('html').css('overflow','');
  }
);

  $('.l-sidebar__drawer-bg').on('click',function(){
      $(this).fadeToggle();
      $('.c-button--header-menu').removeClass('open');
      $('.l-sidebar').removeClass('open');
      $('html').css('overflow','');   
    }
  );